### ISSUE TITLE
Option to use TCP as protocol instead of UDP when querying dns

### ISSUE THREAD

**Issue by jcsantosbr** [gmr/srvlookup#6]
Hi all,

  I've been using this library for a while but I started getting DNS timeouts recently, because the size of the response in my system increased. I believe this is related to the issue asked here: 
[when-do-dns-queries-use-tcp-instead-of-udp](https://serverfault.com/questions/404840/when-do-dns-queries-use-tcp-instead-of-udp)

By default the query will use UDP which doesn't work for long responses (over 512 or 4096 bytes).

  Using the extra parameter `tcp=True` in the `resolver.query` method solved my issue, but with the current code there is no way to pass this option to it.

  Would be OK to add this option in the `srvlookup.lookup` method?

  I can do the code changes myself, I just want to know if this is compatible with the vision for this library and if there is any design guidelines that I whould be aware of. 

Thanks!

**Comment by gmr** [comment]
Seems reasonable to add it ... `tcp=True` makes sense as well. I look forward to a PR :)

**Comment by jcsantosbr** [comment]
@gmr Great! Would you prefer to hardcode the `tcp=True` option or make this a flag (like an optional parameter) in the top level `lookup` method?

I think in the first case, the code is simpler, but it can impact somehow current users of the api.

In the second case we don't impact existing users but the top level api becomes a little more polluted.

**Comment by jcsantosbr** [comment]
Hi @gmr, I created the PR now, sorry for the delay:
https://github.com/gmr/srvlookup/pull/7

Notice that using yapf in the file as it is now, it already generate some changes, I ignored them to avoid noise in this PR, but I will submit another one with the formatting changes.

**Comment by gmr** [comment]
Sorry for the delay in dealing with this. 3.0 will drop with an optional flag to use TCP for DNS.
